version: '3.9'

services:
  project1:
    build:
      context: ./ecommerce-milenio
    container_name: ecommerce-milenio
    ports:
      - "3002:3000" # Mapeia a porta interna 3000 para a 3002
    networks:
      - app-network

  project2:
    build:
      context: ./dashboard-milenio
    container_name: dashboard-milenio
    ports:
      - "3001:3000" # Mapeia a porta interna 3000 para a 3001
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Nginx estará disponível na porta 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Monta o arquivo nginx.conf
    depends_on:
      - project1
      - project2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
